### ISSUE TITLE
Grunt test broken during the testem task?

### ISSUE THREAD

**Issue by toranb** [JarrodCTaylor/fauxjax#16]
Jarrod

It seems a fresh checkout/npm install using node v0.10.36 breaks when the testem task runs (doing grunt test). Is this because of a version bump w/ testem or one of your grunt deps?

thanks !

**Comment by JarrodCTaylor** [comment]
Everything works fine with node v 0.12.X 

You guys stuck on 0.10.X? I'm far from a node pro, I moved to the 12 series when Ember-cli started telling me to. I don't recall having to do anything with fauxjax around that time to get it to work so I am not sure what you are running into.

**Comment by JarrodCTaylor** [comment]
I just realized that I am testing against node 10 on travis which is working as expected https://travis-ci.org/JarrodCTaylor/fauxjax and as I said I am using node 12 locally.

**Comment by toranb** [comment]
Interesting - I'll take a look at 0.10 and see if I can better grok why it's broken *we plan to upgrade on linux soon but at this time we are rocking 0.10 as you mentioned :)

**Comment by dustinfarris** [comment]
I used fauxjax with 0.10 with no issues until last week when I finally got around to upgrading.  (albeit without grunt)

**Comment by toranb** [comment]
@dustinfarris how did you run the test build (like travis) to verify your work? I was using grunt test (but noticed travis was using grunt deploy)

**Comment by dustinfarris** [comment]
I just run `npm test` for my ember-cli projects.  I use [CircleCI](https://circleci.com/) for both open source and private projects which is very similar to Travis (superior IMHO).  This is an example config from one of my projects:

```yml
machine:
  node:
    version: 0.12

dependencies:
  pre:
    - npm config set spin false
    - npm install -g npm@^2
  override:
    - npm install -g bower
    - npm install
    - bower install

deployment:
  staging:
    branch: staging
    commands:
      - EMBER_ENV=staging npm run-script build
      - rsync -qaz --delete -e ssh dist/ web@98.87.76.654:/var/www/myproject
  production:
    branch: master
    commands:
      - EMBER_ENV=production npm run-script build
      - rsync -qaz --delete -e ssh dist/ web@12.23.34.456:/var/www/myproject
```

Circle detects a node project and automatically runs `npm test` — which is translated to `ember test` in a standard ember-cli package.json.
